version: "3.1"

services:
  postgres:
    image: postgres:14.2
    command: postgres -c stats_temp_directory=/tmp
    restart: always
    environment:
      POSTGRES_DATABASE: operator
      POSTGRES_USER: operator
      POSTGRES_PASSWORD: operator
    volumes:
      - ${OPERATOR_DATA_DIR}:/var/lib/postgresql/data
  operator:
    build: .
    restart: always
    environment:
      OPERATOR_EMAIL: ${OPERATOR_EMAIL}
      OPERATOR_PASSWORD: ${OPERATOR_PASSWORD}
      OPERATOR_SMTP_SERVER: ${OPERATOR_SMTP_SERVER}
      OPERATOR_IMAP_SERVER: ${OPERATOR_IMAP_SERVER}
      OPERATOR_INBOX: ${OPERATOR_INBOX}
      OPERATOR_JUNK: ${OPERATOR_JUNK}
      OPERATOR_POSTGRES: postgres
    depends_on:
      - postgres